sudo: required
dist: trusty
language: python
python:
  - "3.6"

cache:
  pip: true
  directories:
  - "$HOME/.cargo"

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUSTFLAGS="-C link-dead-code"
    - RUST_BACKTRACE=1
    - SCCACHE_DIR="$HOME/.cargo/sccache"
    - RUSTC_WRAPPER=sccache


addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  - source ./ci/setup.sh

install:
- pip install setuptools-rust

script:
- ./ci/test.sh
