sudo: required
dist: trusty
language: python

matrix:
  include:
  - python: "3.6"
    enc: FEATURES=python3

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUSTFLAGS="-C link-dead-code"
    - RUST_BACKTRACE=1
    - SCCACHE_DIR="$HOME/.cargo/sccache"
    - RUSTC_WRAPPER=sccache
    
# language: rust
# rust:
#   - nightly
# script:
#   - cargo build --verbose --all
#   - cargo test --verbose --all
