[profile.dev]
opt-level = 0

[profile.release]
lto = true

[workspace]
members = ["act2gif", "core", "devui", "python", "uilib"]

[patch.crates-io.pyo3]
git = "https://github.com/PyO3/pyo3"
branch = "0_5_backports"
