[package]
name = "rogue-gym-python"
version = "0.1.0"
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]

[lib]
name = "rogue_gym_python"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.12.0"
rect-iter = "0.2.0"

[dependencies.numpy]
git = "https://github.com/rust-numpy/rust-numpy.git"
rev = "e372f0bdd61073abbbb48b08b21da5dfa4907b42"

[dependencies.pyo3]
version = "0.4.1"
features = ["extension-module"]

[dependencies.rogue-gym-core]
path = "../core/"
version = "0.1.0"

