[package]
name = "rogue-gym-python"
version = "0.1.0"
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]

[lib]
name = "rogue_gym_python"
crate-type = ["cdylib"]

[dependencies]
rect-iter = "0.1.9"

[dependencies.pyo3]
git = "https://github.com/kngwyu/pyo3"
branch = "native-type-with-generics"
features = ["extension-module"]

[dependencies.numpy]
git = "https://github.com/kngwyu/rust-numpy"
branch = "static-type-check"

[dependencies.rogue-gym-core]
features = ["termion"]
path = "../core/"
version = "0.1.0"

[dependencies.rogue-gym-devui]
path = "../devui/"
version = "0.1.0"
