[package]
name = "rogue-gym-python"
version = "0.1.0"
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]

[lib]
name = "rogue_gym_python"
crate-type = ["cdylib"]

[dependencies]
rect-iter = "0.2.0"

[dependencies.numpy]
git = "https://github.com/kngwyu/rust-numpy.git"
branch = "to-pyarray"

[dependencies.pyo3]
version = "0.4.1"
features = ["extension-module"]

[dependencies.rogue-gym-core]
path = "../core/"
version = "0.1.0"

[dependencies.rogue-gym-devui]
path = "../devui/"
version = "0.1.0"

