[package]
name = "rogue-gym-python"
version = "0.1.0"
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]

[lib]
name = "rogue_gym"
crate-type = ["cdylib"]

[dependencies]
rect-iter = "0.1.9"

[dependencies.pyo3]
version = "0.2.5"
git = "https://github.com/PyO3/pyo3.git"
features = ["extension-module"]

[dependencies.rogue-gym-core]
features = ["termion"]
path = "../core/"
version = "0.1.0"
